services:
  - type: web
    name: ColabNotes
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString